apiVersion: v1
kind: Secret
metadata:
  name: competentie-app-frontend-secret
  namespace: production
data:
  connectionString: VXNlciBJRD1wb3N0Z3JlcztQYXNzd29yZD1yNHE4bzc4cTc4Mjc4bHJpTFVPMzI0OVU4UjM7SG9zdD1wb3N0Z3Jlcy1zdmM7UG9ydD01NDMyO0RhdGFiYXNlPUZyb250ZW5kU2VydmljZURiOwo=
---
    apiVersion: v1
    kind: Service
    metadata:
      name: competentie-app-frontend
      namespace: production
    spec:
      ports:
        - port: 80
      selector:
        app: competentie-app-frontend
---
    apiVersion : apps/v1beta1
    kind: Deployment
    metadata:
      name: competentie-app-frontend
      namespace: production
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: competentie-app-frontend
        spec:
          containers:
            - name: frontend-service
              image: hsleidenmdlo.azurecr.io/competentie-app-frontend:v0.0.1
              imagePullPolicy: Always
              ports:
                - containerPort: 80
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
              env:
                - name: DB_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: competentie-app-frontend-secret
                      key: connectionString