apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: docker.pkg.github.com/hogeschool-leiden/mdlo/demo:v2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 50Mi
