version: '3'
# Used only for local testing.
services:
  frontend-service:
    environment: 
       BROKER_CONNECTION_STRING: amqp://guest:guest@servicebus
       BROKER_EXCHANGE_NAME: CompetentieApp
       DB_CONNECTION_STRING: Server=database;Port=5432;Database=module-domein-db;User Id=postgres;Password=verygoodrootpassword;
       BROKER_QUEUE_NAME: FrontendService
       ENVIRONMENT: DEVELOPMENT
       LOG_LEVEL: TRACE
    depends_on:
      - servicebus
      - database
    build:
      dockerfile: "../../docker/angular/Dockerfile"
      args: 
        sln: CompetentieAppFrontend.sln
        source: .
        runnable: CompetentieAppFrontend.Api.dll
      context: "../src/CompetentieAppFrontend/"
    ports:
      - 80:80
  module-domein-service:
    environment: 
      BROKER_CONNECTION_STRING: amqp://guest:guest@servicebus
      BROKER_EXCHANGE_NAME: CompetentieApp
      DB_CONNECTION_STRING: Server=database;Port=5432;Database=module-domein-db;User Id=postgres;Password=verygoodrootpassword;
      BROKER_QUEUE_NAME: ModuleDomeinService
      ENVIRONMENT: DEVELOPMENT
      LOG_LEVEL: TRACE
    depends_on:
      - servicebus
      - database
    build:
      dockerfile: "../../docker/normal/Dockerfile"
      args: 
        sln: ModuleDomainService.sln
        source: .
        runnable: ModuleDomainService.Application.dll
      context: "../src/ModuleDomainService/"
    ports:
      - 8080:80
  # module-beheer-frontend-service:
  #   environment: 
  #     BROKER_CONNECTION_STRING: amqp://guest:guest@servicebus
  #     BROKER_EXCHANGE_NAME: CompetentieApp
  #     DB_CONNECTION_STRING: Server=database;Port=5432;Database=module-frontend-db;User Id=postgres;Password=verygoodrootpassword;
  #     BROKER_QUEUE_NAME: ModuleFrontend
  #     ENVIRONMENT: DEVELOPMENT
  #     LOG_LEVEL: TRACE
  #
  #   depends_on:
  #     - servicebus
  #     - database
  #   build:
  #     dockerfile: "../../docker/angular/Dockerfile"
  #     args: 
  #       sln: ModuleFrontend.sln
  #       source: .
  #       runnable: ModuleFrontend.Api.dll
  #     context: "../src/ModuleFrontend/"
  #   ports:
  #     - 81:80
  servicebus:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  database:
    image: postgres:12.3-alpine
    environment: 
      POSTGRES_PASSWORD: verygoodrootpassword
    ports:
      - 5432:5432