version: '3'

services:
  demobackend:
    build:
      context: "./../Demo"
      dockerfile: "./Demo.Deployment/Dockerfile"
    ports:
      - 80:80
  demofrontend:
    build:
      context: "./../DemoFrontEnd"
    ports:
      - 8000:80
