version: '3'

services:
  demo-service:
    build:
      context: "./../Demo"
      dockerfile: "./Demo.Deployment/Dockerfile"
    ports:
      - 8081:80
  demo-frontend-service:
    build:
      context: "./../DemoFrontend"
      dockerfile: "./Dockerfile"
    ports: 
      - 8080:80
