name: Release

on:
  push:
    branches:
      - component-testing-pipeline-feature

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: demo

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        testtype: ['Integration', 'Unit', 'Component']
        services: ['DemoFrontend']
    name: Run ${{ matrix.testtype }} tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet install
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '3.1.100'

    - name: Run tests
      run: dotnet test ${{ matrix.services }}/${{matrix.testtype}}/${{matrix.testtype}}.csproj
