name: Release

on:
  push:
    branches:
      - component-testing-pipeline-feature

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: demo

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        testtype: ['ComponentTest', 'Test']
        services: ['DemoFrontend', 'Demo']
    name: Running ${{ matrix.services }} ${{ matrix.testtype }}s
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet install
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '3.1.100'

    - name: Run tests
      run: dotnet test ${{ matrix.services }}/${{ matrix.services }}.Api.${{matrix.testtype}}/${{ matrix.services }}.Api.${{matrix.testtype}}.csproj

  integratie-test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        services: ['DemoFrontend', 'Demo']
        name: Running IntegratieTest on ${{ matrix.services }}
    # services:
    #   database:
    #     image: mysql
    #     ports: 
    #      - 3306:3306
    #     env:
    #       MYSQL_ROOT_PASSWORD: root
    #   service-bus:
    #     ports: 
    #       - 5672:5672
    #     image: rabbitmq:3-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet install
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.100'
      - name: ${{ matrix.services }} component tests
        # env:
        #   DB_HOST: localhost
        #   DB_PORT: 3306
        #   DB_PASS: root
        #   SERVICE_BUS_HOST: localhost
        #   SERVICE_BUS_PORT: 5672
        #   SERVICE_BUS_PASS: guest
        #   SERVICE_BUS_USER: guest

        run: dotnet test ${{ matrix.services }}/${{ matrix.services }}.Api.IntegrationTest/${{ matrix.services }}.Api.IntegrationTest.csproj
        


